const roles=[
  {role:'Senior Public Health Intelligence Manager',org:'Thurrock Council',date:'Nov 2022 - Present',tools:['R','Power BI','SQL','Azure','Git','SystmOne'],points:['Lead a team of five analysts delivering public health intelligence across Thurrock and Mid and South Essex.','Leading the development of 10 Public Health Situation Report publications in one year.','Built 20 automated ward profile dashboards with coded smart narrative.','Developed an API-enabled Thurrock Health Indicators Dashboard with around 10 parameters per indicator.','Researched and published evidence for diabetes management in primary care.','Achieved UKPHR registration in 2025.']},
  {role:'Senior Population Health Management Analyst',org:'NHS Mid and South Essex ICB',date:'Nov 2022 - Mar 2025',tools:['R','SQL','Power BI','SystmOne','Azure','Fingertips'],points:['Delivered Disproportionate Care Law analysis across more than 1 million pseudonymised records.','Scoped and led the CVD LES project across Mid and South Essex.','Designed the Plus Group identification project for inclusion health populations.','Linked datasets from multiple sources to support population health management.','Collaborated with PCN digital leads, health inequalities teams and AGEM.','Developed respiratory risk stratification using machine learning.','Led cancer deep dive work feeding into the Mid and South Essex Cancer Strategy.']},
  {role:'Public Health Specialist',org:'OAUTHC, Ile-Ife, Nigeria',date:'Jun 2021 - Oct 2022',tools:['SPSS','Stata','R','ODK'],points:['Designed and conducted community health surveys on risk factors and health needs.','Contributed to clinical trial design and data collection during the COVID-19 pandemic.','Published research on healthcare worker experiences during COVID-19.','Mentored medical students and resident doctors in epidemiology and data analysis.']},
  {role:'Senior Registrar, Public Health Specialty',org:'OAUTHC, Ile-Ife, Nigeria',date:'May 2016 - May 2021',tools:['SPSS','Stata','ATLAS.ti','EpiData','R'],points:['Facilitated research methodology clinics for resident doctors across OAUTHC.','Conducted adolescent sexual and reproductive health research that informed multiple publications.','Provided consultancy for WHO, HACEY and AHEAD on large-scale surveys.','Led a public health campaign against FGM among secondary school adolescents in Imesi-Ile.','Supported surveillance of polio, malaria, cholera, TB, Lassa fever and COVID-19.']},
  {role:'Registrar, Public Health Specialty',org:'OAUTHC, Ile-Ife, Nigeria',date:'Jan 2014 - May 2016',tools:['SPSS','Stata','EpiData'],points:['Rotated with WHO and state health departments on health surveys and planning.','Developed data analytics and regression analysis skills on large population datasets.','Led advocacy efforts to improve health-seeking behaviour in Imesi-Ile.']}
];
const categoryLabels={phm:'PHM',hi:'Health Inequality',phi:'Public Health Intelligence',ml:'Machine Learning',de:'Data Engineering',ph:'Public Health'};
const projects=[
  {title:'Disproportionate Care Law',cat:'phm',featured:true,desc:'More than 1 million pseudonymised records analysed to identify disproportionate care patterns across Mid and South Essex.',tools:['R','Power BI','SystmOne']},
  {title:'Plus Group / Inclusion Health',cat:'hi',desc:'Scoped and analysed inclusion health populations in Mid and South Essex, then presented the work for PHM steering group approval.',tools:['SQL','R','Azure']},
  {title:'Cancer Deep Dive',cat:'phm',featured:true,desc:'Benchmarked cancer metrics against regional and national data to inform strategic planning across Mid and South Essex.',tools:['R','Fingertips','NHS Digital']},
  {title:'CVD LES - MSE Implementation',cat:'phm',desc:'Scaled cardiovascular LES delivery, improving eligible patient identification and evaluation reporting.',tools:['SystmOne','Excel','Power BI']},
  {title:'Ward Profile Dashboard',cat:'phi',featured:true,desc:'Twenty interactive ward profiles with coded automated smart narrative that update when new data is released.',tools:['Power BI','R','IMD 2025']},
  {title:'Thurrock Health Indicators Dashboard',cat:'phi',featured:true,desc:'API-automated dashboard with around 10 visual parameters per indicator, reducing manual lookup time.',tools:['Power BI','API','Excel Macros']},
  {title:'Respiratory Risk Stratification',cat:'ml',desc:'Machine learning model used to identify high-risk respiratory patients for targeted intervention across MSE PCNs.',tools:['R','Machine Learning','AGEM data']},
  {title:'ETL Pipeline Portfolio',cat:'de',desc:'GitHub repositories covering transaction ingestion, Apache Airflow orchestration and automated analytical pipelines.',tools:['Python','Apache Airflow','SQL']},
  {title:'FGM Campaign - Imesi-Ile',cat:'ph',desc:'Led a public health campaign against FGM among secondary school adolescents in rural Osun State, Nigeria.',tools:['Community engagement','Advocacy','Survey']},
  {title:'COVID-19 Community Response',cat:'ph',desc:'Community mobilisation, surveillance and training of more than 500 health workers in Osun State during COVID-19.',tools:['IDSR','ODK','EOC collaboration']}
];
const publications=[
  {title:'Association between serum vitamins and COVID-19 infection: cross-sectional study of healthcare workers',journal:'BMC Infectious Diseases',year:2026,first:false},
  {title:'Social media engagement and risky sexual behaviours among out-of-school adolescents in Ile-Ife',journal:'Vulnerable Children and Youth Studies',year:2025,first:true},
  {title:'Preferences and motivations for choice of sexual and reproductive health service providers among in-school adolescents',journal:'Texila International Journal of Public Health',year:2025,first:false},
  {title:'COVID-19-related stress, anxiety and vaccine hesitancy among healthcare workers in South-Western Nigeria',journal:'Scientific Reports',year:2025,first:false},
  {title:'Girls at risk: FGM intentions among in-school adolescents of a rural community in Osun State',journal:'European Journal of Contraception and Reproductive Health Care',year:2022,first:true},
  {title:'The factor(s) influencing male involvement in family planning in rural South West Nigeria',journal:'Central African Journal of Public Health',year:2021,first:true},
  {title:'Community perception and determinants of willingness to uptake COVID-19 vaccines in Osun State',journal:'International Journal of Community Medicine and Public Health',year:2021,first:false},
  {title:'Application of quantitative techniques in decision making by healthcare managers in Nigerian tertiary institutions',journal:'Health Services Management Research',year:2016,first:true}
];
const edu=[{year:'2025',degree:'UKPHR Registration',inst:'UK Public Health Register'},{year:'2021',degree:'FWACP - Public Health Medicine',inst:'West African College of Physicians'},{year:'2019',degree:'MPH - Epidemiology & Biostatistics',inst:'Obafemi Awolowo University'},{year:'2016',degree:'MWACP - Public Health',inst:'West African College of Physicians'},{year:'2008',degree:'MBChB - Medicine & Surgery',inst:'Obafemi Awolowo University'}];
const certs=[
  {name:'Microsoft Azure AI Fundamentals',issuer:'Microsoft - Mar 2024',url:'https://learn.microsoft.com/en-us/users/olusolafajobi-3251/credentials/certification/azure-ai-fundamentals'},
  {name:'Microsoft Azure Fundamentals',issuer:'Microsoft - Dec 2023',url:'https://learn.microsoft.com/en-gb/users/olusolafajobi-3251/credentials/certification/azure-fundamentals'},
  {name:'Google Data Analytics Certificate',issuer:'Coursera - Dec 2022',url:'https://www.credly.com/badges/9c1a8c05-63c0-46fb-acff-a1422f40c48f'},
  {name:'Machine Learning with Python',issuer:'Cognitive Class - Dec 2021',url:'https://courses.cognitiveclass.ai/certificates/b9690e7e48784f7191ebc8a0cbb81db0'},
  {name:'Data Analysis with Python',issuer:'Cognitive Class - Nov 2021',url:'https://courses.cognitiveclass.ai/certificates/4f081d796f0a4984bcb5a1dc36db3dee'},
  {name:'Implementation Science in Public Health',issuer:'ISGlobal Barcelona - Apr 2022'},
  {name:'Time Series Analysis - Digital Technologies',issuer:'ISGlobal Barcelona - Apr 2022'},
  {name:'Project Management in Global Health',issuer:'University of Washington - 2019'},
  {name:'Leadership & Management in Health',issuer:'University of Washington - 2016'},
  {name:'ATLAS.ti Certified Trainer',issuer:'2020'},
  {name:'GIS & Remote Sensing in Public Health',issuer:'2018'},
  {name:'M&E of Public Health Programs',issuer:'OAU IPH - 2017'},
  {name:'Health Research Ethics (CITI)',issuer:'CITI Program - May 2021',url:'https://www.citiprogram.org/verify/?w7a6626f8-c07d-4345-95b0-81bb4f353fa4-38518608'},
  {name:'SQL',issuer:'Sololearn',url:'https://www.sololearn.com/Certificate/1060-19142275/pdf/'}
];
const contacts=[{icon:'ti-mail',label:'Email',sub:'sholex111@gmail.com',url:'mailto:sholex111@gmail.com'},{icon:'ti-brand-linkedin',label:'LinkedIn',sub:'olusola-fajobi',url:'https://www.linkedin.com/in/olusola-fajobi-a189a612'},{icon:'ti-brand-github',label:'GitHub',sub:'sholex111',url:'https://github.com/sholex111'},{icon:'ti-article',label:'ResearchGate',sub:'Olusola-Fajobi',url:'https://www.researchgate.net/profile/Olusola-Fajobi'},{icon:'ti-brand-kaggle',label:'Kaggle',sub:'solafajobi',url:'https://www.kaggle.com/solafajobi'}];
function qs(id){return document.getElementById(id)}
function extAttrs(url){return url&&!url.startsWith('mailto:')?' target="_blank" rel="noopener noreferrer"':''}
function projectCard(p){return `<article class="project-card reveal"><span class="category-badge">${categoryLabels[p.cat]}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="chip-row">${p.tools.map(t=>`<span class="chip">${t}</span>`).join('')}</div></article>`}
function renderProjects(items,target){const el=qs(target);if(el)el.innerHTML=items.map(projectCard).join('')}
function renderFilters(){const bar=qs('filterBar');if(!bar)return;const filters=[['all','All'],['phm','PHM'],['hi','Health inequalities'],['phi','Public health intelligence'],['ml','Machine learning'],['de','Data engineering'],['ph','Public health']];bar.innerHTML=filters.map(([key,label])=>`<button class="filter-btn ${key==='all'?'active':''}" type="button" data-filter="${key}">${label}</button>`).join('');bar.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;bar.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');const key=button.dataset.filter;renderProjects(key==='all'?projects:projects.filter(p=>p.cat===key),'projectsContainer');observeReveals()});renderProjects(projects,'projectsContainer')}
function timelineItem(role,index){return `<article class="timeline-item reveal"><div class="timeline-card"><button class="timeline-button" type="button" aria-expanded="${index===0?'true':'false'}"><span><h3>${role.role}</h3><p>${role.org}</p></span><span class="timeline-date">${role.date}</span></button><div class="timeline-details ${index===0?'open':''}"><div class="timeline-inner"><div class="timeline-content"><div class="chip-row">${role.tools.map(t=>`<span class="chip">${t}</span>`).join('')}</div><ul>${role.points.map(point=>`<li>${point}</li>`).join('')}</ul></div></div></div></div></article>`}
function renderTimeline(target,count){const el=qs(target);if(!el)return;el.innerHTML=roles.slice(0,count||roles.length).map(timelineItem).join('');el.addEventListener('click',event=>{const button=event.target.closest('.timeline-button');if(!button)return;const details=button.nextElementSibling;const open=!details.classList.contains('open');details.classList.toggle('open',open);button.setAttribute('aria-expanded',String(open))})}
function renderCredentials(){const eduEl=qs('eduList');if(eduEl)eduEl.innerHTML=edu.map(e=>`<article class="credential-item reveal"><span class="credential-year">${e.year}</span><div><strong>${e.degree}</strong><div class="credential-meta">${e.inst}</div></div></article>`).join('');const certEl=qs('certList');if(certEl)certEl.innerHTML=certs.map(c=>`<a class="credential-item reveal" href="${c.url||'#'}"${extAttrs(c.url)}><i class="ti ti-certificate credential-year"></i><div><strong>${c.name}</strong><div class="credential-meta">${c.issuer}</div></div></a>`).join('')}
function renderPublications(){const stats=qs('publicationStats');if(stats)stats.innerHTML=[['19','Publications'],['76','Citations'],['5','h-index'],['10yrs','Active']].map(s=>`<article><strong>${s[0]}</strong><span>${s[1]}</span></article>`).join('');const list=qs('publicationList');if(list)list.innerHTML=publications.map(p=>`<article class="publication-card reveal"><h3>${p.title}${p.first?'<span class="first-author">First author</span>':''}</h3><div class="publication-meta">${p.journal} · ${p.year}</div></article>`).join('')}
function renderContacts(){const grid=qs('contactGrid');if(grid)grid.innerHTML=contacts.map(c=>`<a class="contact-link reveal" href="${c.url}"${extAttrs(c.url)}><i class="ti ${c.icon}"></i><div><strong>${c.label}</strong><span>${c.sub}</span></div></a>`).join('')}
function setupNav(){const page=document.body.dataset.page;document.querySelectorAll('[data-nav]').forEach(link=>{if(link.dataset.nav===page)link.classList.add('active')});const burger=document.querySelector('.nav-burger');const links=qs('navLinks');if(!burger||!links)return;burger.addEventListener('click',()=>{const open=links.classList.toggle('open');burger.setAttribute('aria-expanded',String(open));burger.setAttribute('aria-label',open?'Close navigation':'Open navigation')});links.addEventListener('click',()=>{links.classList.remove('open');burger.setAttribute('aria-expanded','false')})}
let observer;function observeReveals(){if(observer)observer.disconnect();const els=document.querySelectorAll('.reveal');if(!('IntersectionObserver' in window)){els.forEach(el=>el.classList.add('visible'));return}observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.14});els.forEach(el=>observer.observe(el))}
setupNav();renderProjects(projects.filter(p=>p.featured),'featuredProjects');renderFilters();renderTimeline('homeTimeline',2);renderTimeline('timeline');renderCredentials();renderPublications();renderContacts();observeReveals();
